export default [
  {
    id: 1,
    title: 'Welcome',
    description: null,
    account_id: 1,
    campaign_type: 'ongoing',
    message: 'Hey, What brings you today',
    enabled: true,
    trigger_rules: {
      url: 'https://github.com',
      time_on_page: 10,
    },
    inbox: {
      id: 1,
      channel_type: 'Channel::WebWidget',
      name: 'Web Widget',
    },
    created_at: '2021-05-03T04:53:36.354Z',
    updated_at: '2021-05-03T04:53:36.354Z',
  },
  {
    id: 2,
    title: 'Onboarding Campaign',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    trigger_rules: {
      url: 'https://one-link.kz',
      time_on_page: '20',
    },
    inbox: {
      id: 2,
      channel_type: 'Channel::TwilioSms',
      name: 'Twilio SMS',
    },
    created_at: '2021-05-03T08:15:35.828Z',
    updated_at: '2021-05-03T08:15:35.828Z',
  },
  {
    id: 3,
    title: 'Thanks',
    description: null,
    account_id: 1,
    campaign_type: 'ongoing',
    message: 'Thanks for coming to the show. How may I help you?',
    enabled: false,
    trigger_rules: {
      url: 'https://noshow.com',
      time_on_page: 10,
    },
    inbox: {
      id: 3,
      channel_type: 'Channel::WebWidget',
      name: 'Web Widget 2',
    },
    created_at: '2021-05-03T10:22:51.025Z',
    updated_at: '2021-05-03T10:22:51.025Z',
  },
  {
    id: 4,
    title: 'WhatsApp Campaign',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Hello {{name}}, your order is ready!',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 4,
      channel_type: 'Channel::Whatsapp',
      name: 'WhatsApp Business',
    },
    template_params: {
      name: 'order_ready',
      namespace: 'business_namespace',
      language: 'en_US',
      processed_params: { name: 'John' },
    },
    created_at: '2021-05-03T12:15:35.828Z',
    updated_at: '2021-05-03T12:15:35.828Z',
  },
  {
    id: 5,
    title: 'SMS Promotion',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Get 20% off your next order!',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 5,
      channel_type: 'Channel::Sms',
      name: 'SMS Channel',
    },
    created_at: '2021-05-03T14:15:35.828Z',
    updated_at: '2021-05-03T14:15:35.828Z',
  },
  {
    id: 6,
    title: 'Line Promotion',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Hello from LINE!',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 6,
      channel_type: 'Channel::Line',
      name: 'LINE Channel',
    },
    created_at: '2021-05-03T16:15:35.828Z',
    updated_at: '2021-05-03T16:15:35.828Z',
  },
  {
    id: 7,
    title: 'Messenger Re-engagement',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'We are here if you need help with your order.',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 7,
      channel_type: 'Channel::FacebookPage',
      name: 'Messenger Inbox',
    },
    created_at: '2021-05-03T18:15:35.828Z',
    updated_at: '2021-05-03T18:15:35.828Z',
  },
  {
    id: 8,
    title: 'Instagram Follow-up',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Reply here if you want more details.',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 8,
      channel_type: 'Channel::Instagram',
      name: 'Instagram Inbox',
    },
    created_at: '2021-05-03T20:15:35.828Z',
    updated_at: '2021-05-03T20:15:35.828Z',
  },
  {
    id: 9,
    title: 'Telegram Outreach',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Telegram follow-up',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 9,
      channel_type: 'Channel::Telegram',
      name: 'Telegram Bot',
    },
    created_at: '2021-05-03T21:15:35.828Z',
    updated_at: '2021-05-03T21:15:35.828Z',
  },
  {
    id: 10,
    title: 'TikTok Outreach',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'TikTok re-engagement',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 10,
      channel_type: 'Channel::Tiktok',
      name: 'TikTok Inbox',
    },
    created_at: '2021-05-03T22:15:35.828Z',
    updated_at: '2021-05-03T22:15:35.828Z',
  },
  {
    id: 11,
    title: 'Twitter DM Outreach',
    description: null,
    account_id: 1,
    campaign_type: 'one_off',
    message: 'Twitter DM follow-up',
    enabled: true,
    trigger_rules: {},
    inbox: {
      id: 11,
      channel_type: 'Channel::TwitterProfile',
      name: 'Twitter Inbox',
    },
    created_at: '2021-05-03T23:15:35.828Z',
    updated_at: '2021-05-03T23:15:35.828Z',
  },
];
