---
:verbose: false
:concurrency: <%= ENV.fetch("MEDELEMENT_COMMANDS_SIDEKIQ_CONCURRENCY", 2) %>
:timeout: 25
:max_retries: 3

:queues:
  - medelement_provider_commands

production:
  :concurrency: <%= ENV.fetch("MEDELEMENT_COMMANDS_SIDEKIQ_CONCURRENCY", 2) %>
staging:
  :concurrency: <%= ENV.fetch("MEDELEMENT_COMMANDS_SIDEKIQ_CONCURRENCY", 2) %>
