---
:verbose: false
:concurrency: <%= ENV.fetch("WHATSAPPWEB_HISTORY_SIDEKIQ_CONCURRENCY", 2) %>
:timeout: 25
:max_retries: 3

:queues:
  - whatsappweb_history

production:
  :concurrency: <%= ENV.fetch("WHATSAPPWEB_HISTORY_SIDEKIQ_CONCURRENCY", 2) %>
staging:
  :concurrency: <%= ENV.fetch("WHATSAPPWEB_HISTORY_SIDEKIQ_CONCURRENCY", 2) %>
