---
:verbose: false
:concurrency: <%= ENV.fetch("OUTBOUND_MESSAGES_SIDEKIQ_CONCURRENCY", 3) %>
:timeout: 25
:max_retries: 3

:queues:
  - captain_outbound_messages_v2
  - outbound_messages

production:
  :concurrency: <%= ENV.fetch("OUTBOUND_MESSAGES_SIDEKIQ_CONCURRENCY", 3) %>
staging:
  :concurrency: <%= ENV.fetch("OUTBOUND_MESSAGES_SIDEKIQ_CONCURRENCY", 3) %>
