---
:verbose: false
:concurrency: <%= ENV.fetch("WHATSAPP_INBOUND_SIDEKIQ_CONCURRENCY", 4) %>
:timeout: 25
:max_retries: 3

:queues:
  - whatsapp_inbound

production:
  :concurrency: <%= ENV.fetch("WHATSAPP_INBOUND_SIDEKIQ_CONCURRENCY", 4) %>
staging:
  :concurrency: <%= ENV.fetch("WHATSAPP_INBOUND_SIDEKIQ_CONCURRENCY", 4) %>
