---
:verbose: false
:concurrency: <%= ENV.fetch("TELEPHONY_REALTIME_SIDEKIQ_CONCURRENCY", 3) %>
:timeout: 25
:max_retries: 3

:queues:
  - telephony_realtime

production:
  :concurrency: <%= ENV.fetch("TELEPHONY_REALTIME_SIDEKIQ_CONCURRENCY", 3) %>
staging:
  :concurrency: <%= ENV.fetch("TELEPHONY_REALTIME_SIDEKIQ_CONCURRENCY", 3) %>
